name: "📌 Issue"
description: "기능 추가 또는 버그 수정에 대한 이슈를 생성합니다."
title: "[Issue]: "
labels: []
assignees:
  - ""

body:
  - type: textarea
    id: description
    attributes:
      label: "📌 설명"
      description: "기능 또는 버그에 대한 간단한 설명을 작성해주세요."
      placeholder: "예: 로그인 후 특정 페이지에서 오류 발생"

  - type: textarea
    id: goal
    attributes:
      label: "✅ 목표"
      description: "무엇을 구현하거나 수정할 것인가?"
      placeholder: "예: 로그인 후 정상적으로 대시보드로 이동하도록 수정"

  - type: textarea
    id: tasks
    attributes:
      label: "🛠 필요한 작업"
      description: "필요한 주요 작업들 (예: 코드 수정, 테스트 등)"
      placeholder: |
        - 로그인 API 수정
        - 리디렉션 문제 해결
        - 테스트 코드 작성
    validations:
      required: true

  - type: input
    id: due-date
    attributes:
      label: "📅 완료 예정일"
      description: "완료할 목표 일자"
      placeholder: "YYYY-MM-DD"
